"""Interviewer-only renderer for the answer key.

Lives under ``docs/interviewer/`` so the existing handoff scrub (remove the
interviewer directory before sending the repo to a candidate) sweeps both the
docs and the label dictionary in one motion. ``setup/generate.py`` imports
this module dynamically when present and silently skips when not.
"""

from __future__ import annotations

from pathlib import Path


MISMATCH_LABELS = {
    "M_A": "order=shipped, line=cancelled",
    "M_B": "order=partially_cancelled, all lines fulfilled",
}

REFUND_LABELS = {
    "P_QTY": lambda p: f"shopify partial-line refund: 1 of {p['qty']}",
    "P_POS": lambda _p: (
        "internal_pos: order-level refund where line statuses still "
        "'fulfilled' (cancel-vs-refund nuance)"
    ),
    "P_SPLIT": lambda p: (
        f"shopify_stripe split-tender: ${p['amt']/100:.2f} = "
        f"${p['half']/100:.2f} card + ${p['rest']/100:.2f} store_credit"
    ),
}


def write_answer_key(
    out_path: Path,
    mismatch_log: list[tuple[str, str]],
    refund_log: list[tuple[str, str, dict]],
    reconciliation_amount: float,
) -> None:
    lines_out = [
        "# Interviewer Answer Key",
        "",
        "**Internal only — do not share with candidates.** Regenerated by `setup/generate.py`.",
        "",
        "## Problem 1 — planted facts",
        "",
        "- Reconciliation discrepancy in DATA-123 (gross of test orders): see ticket.",
        "- Reconciliation discrepancy excluding test orders: see ticket.",
        f"- True reconciled non-test revenue: ${reconciliation_amount:,.2f}",
        "",
        "## Status mismatches (5–10 planted, see design doc § \"Seed data\")",
        "",
    ]
    for oid, code in mismatch_log:
        lines_out.append(f"- `{oid}` — {MISMATCH_LABELS[code]}")
    lines_out.append("")
    lines_out.append("## Problem 2 — refund plants")
    lines_out.append("")
    for oid, code, payload in refund_log:
        lines_out.append(f"- `{oid}` — {REFUND_LABELS[code](payload)}")
    lines_out.append("")
    out_path.write_text("\n".join(lines_out))
